stages:
    -   build
    -   deploy

build_image:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  
      
  before_script:
    #- docker info
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_TAG .

    - docker login -u registry -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
    

deploy_image:
  stage: deploy
  image: debian:latest
  when: manual

  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
  script:
    - echo 'running image on ianleedham.dev'
    - ssh -o StrictHostKeyChecking=no gitlab@"$QA_SERVER" 'ls /var/www/html/'
