stages:
    -   build
    -   deploy

build_image:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  
      
  before_script:
    - docker info
    - docker login -u registry -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_TAG ./Frontend
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
    
deploy_image:
  stage: build
  when: manual
  image: alpine:latest
  script:
    - touch ~/.docker/key.pem
    - cat $docker_daemon_key > ~/.docker/key.pem
    - cat ~/.docker/key.pem
