stages:
    -   build
    -   deploy

build_image:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  
      
  before_script:
    - docker info
    - docker login -u registry -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_TAG ./Frontend
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
    
deploy_image:
  stage: deploy
  image: docker:latest
  when: manual

  before_script:
  #check ssh is installed
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)

    # add private key from env to docker file  
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
  script:
    # Re-direct to remote environment.
    - export DOCKER_HOST="ssh://gitlab@ianleedham.dev"
    - echo 'running image on ianleedham.dev'
    # copy docker compose file to server

    # call docker compose file
    - docker-compose -f docker-compose-prod.yml up -d