stages:
    -   build
    -   deploy

build_image:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  
      
  before_script:
    - docker info
    - docker login -u registry -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_TAG ./Frontend
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
    
deploy_image:
  stage: deploy
  image: debian:latest
  when: manual

  before_script:
  #check ssh is installed
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)

    # add private key from env to docker file  
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
  script:
    - echo 'running image on ianleedham.dev'
    # copy docker compose file to server
    - ssh gitlab@ianleedham.dev 'ls /var/www/html/'
    - scp ./docker-compose-prod.yml gitlab@ianleedham.dev:~/portfolio/

    # call docker compose file
    - ssh gitlab@ianleedham.dev cd /home/gitlab/portfolio && docker-compose up