# /docker-compose.yml
version: "3.3"

volumes:
  local_postgres_data: {}

services:
  web:
    build: ./Backend
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./Backend:/app
      - /app/BriansBlog/bin
      - /app/Brialog/obj
    depends_on:
      - db

  db:
    image: postgres:11.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data

  client:
    build: ./Frontend
    ports:
      - "80:80"
      - "4200:4200"
    volumes:
      - ./Frontend:/app
