version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      IMAGE_NAME: ianleedham/profile
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest ./Frontend
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_SHA1
      - run:
          name: Deploy Code
          command: 
            echo  -e "$DOCKER_KEY" > ~/.docker/key.pem
            echo  -e "$DOCKER_CERT" > ~/.docker/cert.pem
            echo  -e "$DOCKER_CA" > ~/.docker/ca.pem

            docker -H=$DOCKER_SERVER --tlscacert=~/.docker/ca.pem --tlskey=~/.docker/key.pem --tlscert=~/.docker/cert.pem --tlsverify info
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: circle_ci_cd
